<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
  protected $table = 'cu_people';
  protected $fillable = [
    'pid',
    'email',
    'fname',
    'lname',
    'website',
    'about',
    'url',
    'address1',
    'address2',
    'city',
    'state',
    'zip',
    'country',
    'games_lvl',
    'subscribed',
    'bounced',
    'first_reff',
    'aid',
    'has_affiliate',
    'affiliate',
    'years_doing_crosfit',
    'primary_shoe',
    'other_shoe',
    'has_competed',
    'crossfit_open',
    'crossfit_team_series',
    'festivus_games',
    'granite_games',
    'wodapalooza',
    'superfit_series',
    'usa_weightlifting',
    'competition_none_of_above',
    'has_diet',
    'primary_diet',
    'other_diet',
    'primary_groceries',
    'other_groceries',
    'has_pre-made_meals',
    'primary_pre-made',
    'other_pre-made',
    'brand_about_time',
    'brand_caffeine_kilos',
    'brand_rx_smart_gear',
    'brand_rpm',
    'brand_fitaid',
    'brand_rogue',
    'brand_rebok',
    'brand_kill_cliff',
    'brand_progenex',
    'brand_doughnuts_deadlifts',
    'brand_puori',
    'brand_rx_bar',
    'brand_o2',
    'brand_territory',
    'brand_rocktape',
    'brand_nobull',
    'brand_nike',
    'brand_other',
    'become_ambassador',
    'birthday',
    'birth_year',
    'birth_month',
    'birth_day',
    'mcid',
    'income',
    'gender',
    'years_doing_crosfit_old',
    'story_prefrence',
    'hash_email',
    'hash_fname',
    'hash_lname',
  ];
}